version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'styled-components'
      - dependency-name: 'eslint'
    groups:
      sainsburys:
        patterns:
          - '@sainsburys-tech/*'
      eslint:
        patterns:
          - '*eslint*'
      next:
        patterns:
          - '*react'
          - '*react-dom'
          - 'next'
      other:
        patterns:
          - '*'
