version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'styled-components'
      - dependency-name: 'eslint'
    groups:
      sainsburys:
        patterns:
          - '@sainsburys-tech/*'
      eslint:
        patterns:
          - '*eslint*'
      next:
        patterns:
          - '*react'
          - '*react-dom'
          - 'next'
        exclude-patterns:
          - '@testing-library/react'
          # ignore all next and react upgrades until we have a solution for Argos header
          - '*react'
          - '*react-dom'
          - 'next'
          # ignore all tailwind upgrades until Design Systems have upgraded Fable to Tailwind 4
          - '*tailwindcss*'
      other:
        patterns:
          - '*'
