resources:
  requests:
    memory: '512Mi'
    cpu: '600m'
  limits:
    memory: '512Mi'
    cpu: '2'
envVariables:
  DEV_STUB: 'true'
  OVERRIDE_FLAGS: 'true'
  SHELL_ENV: 'production'
  APP_BASE_URL: 'https://basket-gm-basket-wishlist-ui.int.dev.jspaas.uk'
