name: SonarQube Quality Gate
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest # update to run on "self-hosted" after bosun onboarding
    timeout-minutes: 20
    env:
      GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: sainsburys-tech/sonarqube-typescript@v1
        with:
          sonar-host-url: ${{ vars.SONAR_ORG_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_ORG_TOKEN }}
          project-key: 'sainsburys-tech_gm-basket-wishlist-ui_8ed6ab47-2f44-4234-bece-e72497e4951b'
          node-version-file: '.nvmrc'
          packages-token: ${{ secrets.READ_PACKAGES_TOKEN }}
