name: On PR open
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-analysis:
    name: Code Analysis
    # Skip SonarQube analysis for Dependabot PRs
    if: github.actor != 'dependabot[bot]'
    runs-on:
      - self-hosted
      - build
    timeout-minutes: 20
    env:
      GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: sainsburys-tech/sonarqube-typescript@v1
        with:
          sonar-host-url: ${{ vars.SONAR_ORG_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_ORG_TOKEN }}
          project-key: 'sainsburys-tech_gm-basket-wishlist-ui_8ed6ab47-2f44-4234-bece-e72497e4951b'
          node-version-file: '.nvmrc'
          test-command: npm run # update with command after setting up jest and RTL
          packages-token: ${{ secrets.READ_PACKAGES_TOKEN }}
  code-checks:
    uses: ./.github/workflows/code-checks.yaml
  build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      bosun-config: ./bosun.yaml
      image-tags: $ECR/$BOSUN_PRODUCT/$BOSUN_APP:$SHORT_SHA-dev
    secrets: inherit

  deploy-feature-branch:
    needs: [build, code-checks]
    uses: ./.github/workflows/reusable-deploy.yaml
    with:
      bosun-config: ./bosun.yaml
      environment: dev
      job-name: 'deploy-feature-branch'
      tags: ${{ needs.build.outputs.tags }}
      bosun-yaml-overrides: "{bosun: {deployment: {config: {envVariables: {APP_BASE_URL: 'https://basket-gm-basket-wishlist-ui-${{ github.event.pull_request.number }}.int.dev.jspaas.uk'}}}}}"
    secrets: inherit

  run-playwright:
    needs: deploy-feature-branch
    uses: ./.github/workflows/playwright.yaml
    with:
      app-base-url: 'https://basket-gm-basket-wishlist-ui-${{ github.event.pull_request.number }}.int.dev.jspaas.uk'
    secrets: inherit
