name: Playwright Tests

on:
  workflow_call:
    inputs:
      app-base-url:
        description: 'The base URL used for the Playwright tests'
        required: true
        type: string
jobs:
  playwright-version:
    runs-on:
      - self-hosted
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Get Playwright version from package.json
        id: get-playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(jq -r '.devDependencies["@playwright/test"]' package.json | sed 's/^\^//')
          echo "PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}" >> $GITHUB_ENV
    outputs:
      playwright-version: ${{ env.PLAYWRIGHT_VERSION }}

  playwright-test:
    needs: playwright-version
    env:
      GITHUB_PACKAGES_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APP_BASE_URL: ${{ inputs.app-base-url }}
      HOME: /root # Set HOME to root to resolve Firefox issue
    runs-on:
      - self-hosted
      - build
    container:
      image: mcr.microsoft.com/playwright:v${{ needs.playwright-version.outputs.playwright-version }}-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Set app base url as ENV variable for Playwright
        run: echo "APP_BASE_URL=${{ inputs.app-base-url }}" >> $GITHUB_ENV
      - name: Run Playwright tests
        run: npm run e2e --grep="@desktop|@mobile"
    outputs:
      status: ${{ job.status }}
