name: Undeploy
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: The environment from which to undeploy it
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
      deploy-suffix:
        description: Optional suffix to undeploy (used for previews or sub-environments)
        required: false
jobs:
  undeploy:
    runs-on:
      - self-hosted
      - deploy
    steps:
      - uses: actions/checkout@v4
      - uses: sainsburys-tech/bosun-actions-setup@v1
        name: Setup
        id: setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          app-name: 'gm-basket-wishlist-ui'
      - uses: sainsburys-tech/bosun-actions-undeploy@v1
        name: Undeploy
        with:
          app: 'gm-basket-wishlist-ui'
          environment: ${{ inputs.environment || 'dev' }}
          deploy-suffix: ${{ inputs.deploy-suffix || github.event.pull_request.number || '' }}
